[package]
name = "sfhash"
version = "0.1.1"
edition = "2018"
license = "LGPL-2.1"
description = "The `Hsieh Hash` or `SuperFastHash` function"
repository = "https://github.com/xiphoseer/sfhash"
readme = "README.md"

[dependencies]
